
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = "+\xc8\x95\x9f\xbf\x01\xb0\x90{'\xb5p\xe6,\x07p"
    
_lr_action_items = {'COUNT':([0,2,13,14,16,],[1,10,1,1,20,]),'RPAREN':([2,7,10,11,12,15,20,],[-10,-8,-11,-7,16,19,-9,]),'SYMBOL':([0,2,5,6,7,9,10,11,12,13,14,15,20,],[2,-10,2,2,-8,2,-11,-7,2,2,2,2,-9,]),'EQUALS':([2,3,5,7,8,10,11,17,19,20,],[-10,-3,-6,-8,14,-11,-7,-4,-5,-9,]),'ADD':([2,3,5,7,8,10,11,17,18,19,20,],[-10,-3,-6,-8,13,-11,-7,-4,13,-5,-9,]),'LPAREN':([0,1,2,5,6,7,9,10,11,12,13,14,15,20,],[6,9,-10,6,6,-8,6,-11,-7,6,6,6,6,-9,]),'$end':([2,3,4,5,7,8,10,11,17,18,19,20,],[-10,-3,0,-6,-8,-1,-11,-7,-4,-2,-5,-9,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'chemical_equation':([0,],[4,]),'molecule':([0,13,14,],[3,17,3,]),'species':([0,5,6,9,12,13,14,15,],[7,11,7,7,11,7,7,11,]),'species_list':([0,6,9,13,14,],[5,12,15,5,5,]),'chemical_formula':([0,14,],[8,18,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> chemical_equation","S'",1,None,None,None),
  ('chemical_equation -> chemical_formula','chemical_equation',1,'p_equation','/Users/ylou/Dropbox/code/python/pychem/formula/parser.py',29),
  ('chemical_equation -> chemical_formula EQUALS chemical_formula','chemical_equation',3,'p_equation','/Users/ylou/Dropbox/code/python/pychem/formula/parser.py',30),
  ('chemical_formula -> molecule','chemical_formula',1,'p_chemical_formula','/Users/ylou/Dropbox/code/python/pychem/formula/parser.py',39),
  ('chemical_formula -> chemical_formula ADD molecule','chemical_formula',3,'p_chemical_formula','/Users/ylou/Dropbox/code/python/pychem/formula/parser.py',40),
  ('molecule -> COUNT LPAREN species_list RPAREN','molecule',4,'p_molecule_species','/Users/ylou/Dropbox/code/python/pychem/formula/parser.py',51),
  ('molecule -> species_list','molecule',1,'p_molecule_species','/Users/ylou/Dropbox/code/python/pychem/formula/parser.py',52),
  ('species_list -> species_list species','species_list',2,'p_species_list','/Users/ylou/Dropbox/code/python/pychem/formula/parser.py',61),
  ('species_list -> species','species_list',1,'p_species_list','/Users/ylou/Dropbox/code/python/pychem/formula/parser.py',62),
  ('species -> LPAREN species_list RPAREN COUNT','species',4,'p_species_enclosed','/Users/ylou/Dropbox/code/python/pychem/formula/parser.py',71),
  ('species -> SYMBOL','species',1,'p_species','/Users/ylou/Dropbox/code/python/pychem/formula/parser.py',77),
  ('species -> SYMBOL COUNT','species',2,'p_species','/Users/ylou/Dropbox/code/python/pychem/formula/parser.py',78),
]
